# Generated by Django 2.2 on 2019-07-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
