# Generated by Django 2.2.3 on 2019-07-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_dataset_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
