# Generated by Django 2.2 on 2019-07-17 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datastore', '0005_dataset_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='access_granted',
            field=models.ManyToManyField(null=True, related_name='datasets_accessible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
