# Generated by Django 2.2 on 2019-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
