# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Use Ubuntu 16.04 as basis for VM
  config.vm.box = "ubuntu/xenial64"

  # ==== PORT CONFIGURATION ====

  # Apache Web Server
  config.vm.network :forwarded_port, guest: 80, host: 4567

  # Jupyter Notebook
  config.vm.network :forwarded_port, guest: 8888, host: 8888

  # Jupyter Notebook Alternative Port
  config.vm.network :forwarded_port, guest: 8889, host: 8889

  # Ganache Blockchain
  config.vm.network :forwarded_port, guest: 8545, host: 8545

  # Django - Open a few ports for testing multiple servers
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 8001, host: 8001
  config.vm.network :forwarded_port, guest: 8002, host: 8002

  # ==== VM CONFIGURATION ====

  config.vm.provider "virtualbox" do |vb|

    # Amount of memory used by VM (1GB)
    vb.memory = "1024"    
    #vb.memory = "2048"

    # Display VirtualBox GUI when booting the machine
    # vb.gui = true

    # Disable creation of log file
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    # Hard-code virtual ethernet cable connection
    # This prevents SSH auth method: private key from getting stuck
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  # ==== SCRIPTS TO RUN AFTER STARTUP ====

  config.vm.provision :shell, path: "./scripts/bootstrap.sh"
  
end

# For a complete reference of configuration options:
# https://docs.vagrantup.com.
