# Generated by Django 3.0 on 2023-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_ethereum_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Data Provider'), (1, 'Data Requester')], default=0),
        ),
    ]
