# Generated by Django 2.2.3 on 2019-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190709_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
