# Generated by Django 2.2 on 2023-01-12 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for_decision_support', models.BooleanField(default=False)),
                ('use_for_disease_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResearchPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for_methods_development', models.BooleanField(default=False)),
                ('use_for_reference_or_control_material', models.BooleanField(default=False)),
                ('use_for_research_concerning_populations', models.BooleanField(default=False)),
                ('use_for_research_ancestry', models.BooleanField(default=False)),
                ('use_for_biomedical_research', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HMBResearchPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for_research_concerning_fundamental_biology', models.BooleanField(default=False)),
                ('use_for_research_concerning_genetics', models.BooleanField(default=False)),
                ('use_for_research_concerning_drug_development', models.BooleanField(default=False)),
                ('use_for_research_concerning_any_disease', models.BooleanField(default=False)),
                ('use_for_research_concerning_age_categories', models.BooleanField(default=False)),
                ('use_for_research_concerning_gender_categories', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_restrictions', models.BooleanField()),
                ('open_to_general_research_and_clinical_care', models.BooleanField()),
                ('open_to_HMB_research', models.BooleanField()),
                ('open_to_population_and_ancestry_research', models.BooleanField()),
                ('open_to_disease_specific', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='ResearchPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HMB_research_purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.HMBResearchPurpose')),
                ('clinical_purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ClinicalPurpose')),
                ('general_research_purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralResearchPurpose')),
            ],
        ),
        migrations.CreateModel(
            name='LuceRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('licence', models.IntegerField(default=1)),
                ('link', models.CharField(max_length=255, null=True)),
                ('consent_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ConsentContract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consentcontract',
            name='research_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ResearchPurpose'),
        ),
        migrations.AddField(
            model_name='consentcontract',
            name='restrictions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Restrictions'),
        ),
        migrations.AddField(
            model_name='consentcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
