# -*- mode: ruby -*-
# vi: set ft=ruby :


# LuceVM Setup
Vagrant.configure("2") do |config|


  config.vm.define "lucevm", primary: true do |lucevm|
    # trusty = Ubuntu 14.04.6 LTS
    lucevm.vm.box = "ubuntu/trusty64"
    lucevm.vm.network "private_network", ip: "192.168.72.2"
  end

end



# PostgreSQL Setup

# Used to check later if Database was already provisioned
$script = <<SCRIPT
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  
  config.vm.define "psql" do |psql|
    # Create note that system was provisioned
    psql.vm.provision "shell", inline: $script
    psql.vm.network "private_network", ip: "192.168.72.3"
    psql.vm.network :forwarded_port, guest: 5432, host: 15432
  end

end

# Apply some configuration with old version of settings
Vagrant.configure("1") do |config|

  config.vm.define "psql" do |psql|
    # trusty = Ubuntu 14.04.6 LTS
    psql.vm.box = "ubuntu/trusty64"
    psql.vm.host_name = "postgresql" 
    psql.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
    
    # Provision is performed only the first time machine is started
    psql.vm.provision :shell, :path => "scripts/psql_bootstrap.sh"
  end

end